---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository 
metadata:
  name: capi-aws 
spec:
  interval: 29s
  ref:
    branch: main
  url: https://github.com/kgamanji/cluster-api-helm-chart 
